### ISSUE TITLE
Error: You must supply an options object - but options object is being supplied

### ISSUE THREAD

**Issue by Liam-OShea** [rollup/stream#14]
I am trying to use this module but it seems to have an issue with the options object. Even though I am providing one, it is returning Error: You must supply an options object. Please see report below.

- @rollup/stream Version: ^2.0.0
- Rollup Version: 
- "peerDependencies": {
        "rollup": "^2.35.1"
      }
- Operating System (or Browser): Macbook Air M1
- Node Version: 16

### How Do We Reproduce?
**gulpfile.js**

function bundle() {
  const options = {input : "src/main.js"}
  return rollupStream(options)
  .pipe(source("bundle.js"))
  .pipe(dest("dist"))
}
exports.default = series(bundle);

run using gulp CLI

### Expected Behavior
Bundling works without issue

### Actual Behavior
Error: You must supply an options object
    at getOutputOptionsAndPluginDriver (/Users/liam/Documents/Work/ProofOfConcept/gulpinject/node_modules/rollup/dist/shared/rollup.js:23604:15)
    at handleGenerateWrite (/Users/liam/Documents/Work/ProofOfConcept/gulpinject/node_modules/rollup/dist/shared/rollup.js:23587:74)
    at Object.generate (/Users/liam/Documents/Work/ProofOfConcept/gulpinject/node_modules/rollup/dist/shared/rollup.js:23548:20)
    at build (/Users/liam/Documents/Work/ProofOfConcept/gulpinject/node_modules/@rollup/stream/dist/index.js:10:37)

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.
